version: '3.8'
services:
  postgres:
    image: postgres:14 # or your preferred version
    container_name: nest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: July2002@27
      POSTGRES_DB: eventeir7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
